apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-demo-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: "5044e54e-3ee6-43ea-b7bf-d4596dbfadae"
  labels:
    azure.workload.identity/use: "true"