apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-demo-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: "c16bcce0-6550-44b0-86b8-4c8e063b9597"
  labels:
    azure.workload.identity/use: "true"