apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-demo-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: "${workload_identity_client_id}"
  labels:
    azure.workload.identity/use: "true"